/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <ctype.h>

void
calculadora_1(char *host)
{
	CLIENT *clnt;
	int opcion;
	int operacion;

	double *result_d;
	double arg1_d, arg2_d;
	int *result_i;
	int arg1_i, arg2_i;
	vector3D *result_v;
	vector3D arg1_v, arg2_v;
	matrix *result_m;
	matrix arg1_m, arg2_m;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, COMPLETA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	do{
		// MENU PRINCIPAL
		printf("ELIJA UNA OPCION DE LA CALCULADORA:\n");
		printf("\t1. Operaciones Basicas\n");
		printf("\t2. Operaciones Logaritmicas\n");
		printf("\t3. Operaciones Trigonometricas\n");
		printf("\t4. Operaciones Vectoriales\n");
		printf("\t5. Operaciones Matriciales\n");
		printf("\t6. Salir del Programa\n");
		scanf("%d", &opcion);
		printf("\n");

		switch(opcion)
		{
			case 1: // OPERACIONES BASICAS
				do{
					printf("ELIJA UNA OPERACION:\n");
					printf("\t1. Suma\n");
					printf("\t2. Resta\n");
					printf("\t3. Multiplicacion\n");
					printf("\t4. Division\n");
					printf("\t5. Modulo\n");
					printf("\t6. Potencia\n");
					printf("\t7. Raiz\n");
					printf("\t8. Factorial\n");
					printf("\t9. Volver al menu principal\n");
					scanf("%d", &operacion);
					printf("\n");

					switch(operacion)
					{
						case 1:	// Suma
							printf("Introduzca el primer numero: ");
							scanf("%lf", &arg1_d);
							printf("Introduzca el segundo numero: ");
							scanf("%lf", &arg2_d);
							printf("\n");

							result_d = suma_1(arg1_d, arg2_d, clnt);
							
							if (result_d == (double *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: %f + %f = %f\n\n",arg1_d,arg2_d,*result_d);
							}
						break;

						case 2:	// Resta
							printf("Introduzca el primer numero: ");
							scanf("%lf", &arg1_d);
							printf("Introduzca el segundo numero: ");
							scanf("%lf", &arg2_d);
							printf("\n");

							result_d = resta_1(arg1_d, arg2_d, clnt);

							if (result_d == (double *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: %f - %f = %f\n\n",arg1_d,arg2_d,*result_d);
							}
						break;

						case 3:	// Multiplicacion
							printf("Introduzca el primer numero: ");
							scanf("%lf", &arg1_d);
							printf("Introduzca el segundo numero: ");
							scanf("%lf", &arg2_d);
							printf("\n");

							result_d = multiplica_1(arg1_d, arg2_d, clnt);

							if (result_d == (double *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: %f * %f = %f\n\n",arg1_d,arg2_d,*result_d);
							}
						break;

						case 4:	// Division
							printf("Introduzca el dividendo: ");
							scanf("%lf", &arg1_d);
							printf("Introduzca el divisor: ");
							scanf("%lf", &arg2_d);
							printf("\n");

							if(arg2_d == 0)
							{
								printf("No se puede dividir entre 0\n");
							}
							else
							{
								result_d = divide_1(arg1_d, arg2_d, clnt);
								if (result_d == (double *) NULL) {
									clnt_perror (clnt, "call failed");
								}
								else{
									printf("Resultado: %f / %f = %f\n\n",arg1_d, arg2_d,*result_d);
								}
							}
						break;

						case 5:	// Modulo
							printf("Introduzca un numero: ");
							scanf("%d", &arg1_i);
							printf("Introduzca el modulo: ");
							scanf("%d", &arg2_i);
							printf("\n");

							if(arg2_i == 0)
							{
								printf("No se puede hacer modulo 0\n\n");
							}
							else
							{
								result_i = modulo_1(arg1_i, arg2_i, clnt);
								if (result_i == (int *) NULL) {
									clnt_perror (clnt, "call failed");
								}
								else{
									printf("Resultado: %d mod %d = %d\n\n",arg1_i,arg2_i,*result_i);
								}
							}

						break;

						case 6:	// Potencia
							printf("Introduzca un numero: ");
							scanf("%d", &arg1_i);
							printf("Introduzca a cuanto quiere elevarlo: ");
							scanf("%d", &arg2_i);
							printf("\n");

							result_i = potencia_1(arg1_i, arg2_i, clnt);
						
							if (result_i == (int *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: %d ^ %d = %d\n\n",arg1_i,arg2_i,*result_i);
							}
						break;

						case 7:	// Raiz 	NO FUNCIONA
							printf("Introduzca un numero: ");
							scanf("%lf", &arg1_d);
							printf("Introduzca la raiz (un numero entero positivo): ");
							scanf("%d", &arg2_i);
							printf("\n");

							if(arg2_i <= 0)
							{
								printf("La raiz debe ser un numero positivo diferent de 0\n\n");
							}
							else if((arg2_i % 2 == 0) && arg1_d < 0)
							{
								printf("No se puede hacer la raiz %d de un numero negativo\n\n", arg2_i);
							}
							else
							{
								result_d = raiz_1(arg1_d, arg2_i, clnt);
								if (result_d == (double *) NULL) {
									clnt_perror (clnt, "call failed");
								}
								else{
									printf("Resultado: %f ^ 1/%d = %f\n\n",arg1_d,arg2_i,*result_d);
								}
							}
						break;

						case 8:	// Factorial
							printf("Introduzca un numero (no muy grande): ");
							scanf("%d", &arg1_i);
							printf("\n");
							
							result_i = factorial_1(arg1_i, clnt);

							if (result_i == (int *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: %d! = %d\n\n",arg1_i,*result_i);
							}
						break;
						
						case 9:
							printf("Volviendo al menu principal...\n\n");
						break;

						default: 
							printf("Opcion no valida\n\n"); 
						break;
					}
				} while (operacion!=9);
			break;

			case 2: // OPERACIONESE LOGARITMICAS
				do{
					printf("ELIJA UNA OPERACION:\n");
					printf("\t1. Logaritmo base X\n");
					printf("\t2. Logaritmo neperiano\n");
					printf("\t3. Logaritmo base 10\n");
					printf("\t4. Volver al menu principal\n");
					scanf("%d", &operacion);
					printf("\n");

					switch(operacion)
					{
						case 1:	// Logaritmo base X
							printf("Introduzca un numero (positivo): ");
							scanf("%d", &arg1_i);
							printf("Introduzca la base: ");
							scanf("%d", &arg2_i);
							printf("\n");
							if(arg2_i <= 0)
							{
								printf("No se puede hacer logaritmo con base menor o igual a 0\n\n");
							}
							else if(arg1_i < 0)
							{
								printf("No existe el logaritmo de un numero negativo\n\n");
							}
							else
							{
								result_d = logaritmo_1(arg1_i, arg2_i, clnt);
								if (result_d == (double *) NULL) {
									clnt_perror (clnt, "call failed");
								}
								else{
									printf("Resultado: log %d base %d = %f\n\n",arg1_i,arg2_i,*result_d);
								}
							}
						break;
						case 2:	// Logaritmo neperiano
							printf("Introduzca un numero: ");
							scanf("%d", &arg1_i);
							printf("\n");

							if(arg1_i < 0)
							{
								printf("No existe el logaritmo de un numero negativo\n\n");
							}
							else
							{
								result_d = log_n_1(arg1_i, clnt);
								if (result_d == (double *) NULL) {
									clnt_perror (clnt, "call failed");
								}
								else{
									printf("Resultado: logn %d = %f\n\n",arg1_i,*result_d);
								}
							}
						break;
						case 3:	// Logaritmo base 10
							printf("Introduzca un numero: ");
							scanf("%d", &arg1_i);
							printf("\n");
							if(arg1_i < 0)
							{
								printf("No existe el logaritmo de un numero negativo\n\n");
							}
							else
							{
								result_d = log10_1(arg1_i, clnt);
								if (result_d == (double *) NULL) {
									clnt_perror (clnt, "call failed");
								}
								else{
									printf("Resultado: log10 %d = %f\n\n",arg1_i,*result_d);
								}
							}
						break;
						
						case 4:
							printf("Volviendo al menu principal...\n\n");
						break;

						default: 
							printf("Opcion no valida\n\n"); 
						break;
					}
				} while (operacion!=4);
			break;

			case 3: // OPERACIONES TRIGONOMETRICAS
				do{
					printf("ELIJA UNA OPERACION:\n");
					printf("\t1. Seno\n");
					printf("\t2. Coseno\n");
					printf("\t3. Tangente\n");
					printf("\t4. Volver al menu principal\n");
					scanf("%d", &operacion);
					printf("\n");

					switch(operacion)
					{
						case 1:
							printf("Introduzca los grados: ");
							scanf("%lf", &arg1_d);
							printf("\n");

							result_d = seno_1(arg1_d, clnt);
							
							if (result_d == (double *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: sin(%f) = %f\n\n",arg1_d,*result_d);
							}
						break;
						case 2:
							printf("Introduzca los grados: ");
							scanf("%lf", &arg1_d);
							printf("\n");

							result_d = coseno_1(arg1_d, clnt);
							
							if (result_d == (double *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: cos(%f) = %f\n\n",arg1_d,*result_d);
							}
						break;
						case 3:
							printf("Introduzca los grados: ");
							scanf("%lf", &arg1_d);
							printf("\n");

							result_d = tangente_1(arg1_d, clnt);
							
							if (result_d == (double *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else{
								printf("Resultado: tan(%f) = %f\n\n",arg1_d,*result_d);
							}
						break;
						
						case 4:
							printf("Volviendo al menu principal...\n\n");
						break;

						default: 
							printf("Opcion no valida\n\n");
						break;
					}
				} while (operacion!=4);
			break;

			case 4: // OPERACIONES VECTORIALES
				do{
					printf("ELIJA UNA OPERACION:\n");
					printf("\t1. Suma Vectorial\n");
					printf("\t2. Resta Vectorial\n");
					printf("\t3. Multiplicacion por Escalar\n");
					printf("\t4. Producto Escalar\n");
					printf("\t5. Producto Vectorial\n");
					printf("\t6. Volver al menu principal\n");
					scanf("%d", &operacion);
					printf("\n");

					switch(operacion)
					{
						case 1:
							printf("Introduzca el primer vector: \n");
							printf("x: ");
							scanf("%d", &arg1_v.x);
							printf("y: ");
							scanf("%d", &arg1_v.y);
							printf("z: ");
							scanf("%d", &arg1_v.z);
						
							printf("Introduzca el segundo vector: \n");
							printf("x: ");
							scanf("%d", &arg2_v.x);
							printf("y: ");
							scanf("%d", &arg2_v.y);
							printf("z: ");
							scanf("%d", &arg2_v.z);
							result_v = sumavectorial_1(arg1_v, arg2_v, clnt);

							if (result_v == (vector3D *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							else
							{
								printf("Resultado: (%d, %d, %d) + (%d, %d, %d) = (%d, %d, %d)\n\n",
										arg1_v.x, arg1_v.y, arg1_v.z, arg2_v.x, arg2_v.y, arg2_v.z,
										result_v->z, result_v->y, result_v->z);
							}
						break;
						case 2:
						break;
						case 3:
						break;
						case 4:
						break;
						case 5:
						break;
						
						case 6:
							printf("Volviendo al menu principal...\n\n");
						break;

						default: 
							printf("Opcion no valida\n\n");
						break;
					}

				} while (operacion!=6);
			break;

			case 5: // OPERACIONES MATRICIALES
				do{
					printf("ELIJA UNA OPERACION:\n");
					printf("\t1. Suma Matricial\n");
					printf("\t2. Resta Matricial\n");
					printf("\t3. Multiplicacion Matricial\n");
					printf("\t4. Volver al menu principal\n");
					scanf("%d", &operacion);
					printf("\n");

					switch(operacion)
					{
						case 1:
						break;
						case 2:
						break;
						case 3:
						break;
						
						case 4:
							printf("Volviendo al menu principal...\n\n");
						break;

						default: 
							printf("Opcion no valida\n\n");
							printf("\n"); 
						break;
					}
				} while (operacion!=4);
			break;

			case 6:	// SALIR
				printf("Saliendo del programa...\n");
			break;

			default: 
				printf("Opcion no valida\n\n");
			break;
		}
	} while (opcion != 6);
/*

	result_15 = sumavectorial_1(sumavectorial_1_arg1, sumavectorial_1_arg2, clnt);
	if (result_15 == (vector3D *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = restavectorial_1(restavectorial_1_arg1, restavectorial_1_arg2, clnt);
	if (result_16 == (vector3D *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = multporescalar_1(multporescalar_1_arg1, multporescalar_1_arg2, clnt);
	if (result_17 == (vector3D *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_18 = productoescalar_1(productoescalar_1_arg1, productoescalar_1_arg2, clnt);
	if (result_18 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_19 = productovectorial_1(productovectorial_1_arg1, productovectorial_1_arg2, clnt);
	if (result_19 == (vector3D *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_20 = sumamatricial_1(sumamatricial_1_arg1, sumamatricial_1_arg2, clnt);
	if (result_20 == (matrix *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_21 = restamatricial_1(restamatricial_1_arg1, restamatricial_1_arg2, clnt);
	if (result_21 == (matrix *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_22 = multmatricial_1(multmatricial_1_arg1, multmatricial_1_arg2, clnt);
	if (result_22 == (matrix *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_1 (host);
exit (0);
}
